parameters:
#    emm_user.example.class: EMM\UserBundle\Example

services:
#    emm_user.example:
#        class: %emm_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
